### ISSUE TITLE
huge eval switch

### ISSUE THREAD

**Issue by tissatussa** [Gourab-Ghosh/timecat-rs#3]
during and after this game i was wondering about the way the evaluation values switched quit a bit for consecutive moves, starting at about 18.a4 (Timecat v1.35.4 played White here) :

-0.77
-1.14
-2.58
+1.30 !?
+1.77 !?
-0.31
-2.28
-1.94
...

![Timecat-eval-switch](https://github.com/user-attachments/assets/ebb80d5c-35e2-47f5-9ac3-062959b608a1)

In this phase of the game i see Timecat prefers to spend about max 10 seconds per move, and that max is slowly climbing, although some positions might demand more or less time. Its judgement seems 'drunk', not having a clear understanding of the complexity of the position.

Are its evals a 'current value' at the moment the search is stopped - abruptly ? Then i consider this a bug.

I can imagine an engine may be surprised by the opponent move and then 'admits' its eval is lower than calculated at the previous move, but i seldom saw such a huge eval switch. Is this due to using a NN for the evaluation ? When do you stop the search ?

It's a part of this 5m+3s game :

```
[Event "engine vs engine"]
[Site "Holland @ https://lichess.org/3LTEfRLm "]
[Date "2024.09.08"]
[Round "?"]
[White "Timecat v1.35.4 NNUE"]
[Black "Torch v2 NN"]
[Result "0-1"]
[ECO "E10"]
[GameDuration "00:13:33"]
[Opening "Queen's pawn game"]
[PlyCount "112"]
[TimeControl "300+3"]

1. d4 {+0.63/7 0.42s} Nf6 {-0.22/24 11s} 2. c4 {+0.48/11 0.92s}
e6 {-0.27/25 8.7s} 3. Nf3 {+0.30/11 1.4s} d5 {-0.19/23 6.0s}
4. Nc3 {+0.45/11 1.9s} Bb4 {-0.19/26 53s} 5. Bg5 {+0.67/12 2.4s}
dxc4 {-0.14/24 8.4s} 6. e4 {+1.54/13 2.9s} h6 {-0.11/23 6.5s}
7. Bxf6 {+1.09/15 3.4s} Qxf6 {-0.14/25 8.5s} 8. Bxc4 {+0.95/13 3.9s}
c5 {-0.19/26 12s} 9. O-O {+1.07/14 4.4s} cxd4 {-0.12/25 5.1s}
10. Nb5 {+0.54/13 4.9s} Qe7 {-0.12/26 6.4s} 11. a3 {+0.71/12 5.4s}
Bc5 {+0.20/21 4.8s} 12. e5 {-0.25/13 5.9s} O-O {+0.19/26 11s}
13. b4 {-0.21/15 6.4s} Bb6 {+0.47/22 6.4s} 14. Qe2 {+0.39/14 6.9s}
Rd8 {+0.31/28 56s} 15. Qe4 {+0.70/14 7.4s} Nc6 {+0.53/22 4.9s}
16. Bd3 {+0.29/13 7.9s} f5 {+0.55/21 4.6s} 17. exf6 {-1.57/13 8.4s}
gxf6 {+0.57/20 6.1s} 18. a4 {-0.77/12 8.9s} f5 {+0.66/21 6.6s}
19. Qf4 {-1.14/14 9.5s} a6 {+0.91/23 9.3s} 20. a5 {-2.58/13 10.0s}
axb5 {+0.82/25 7.7s} 21. axb6 {+1.30/15 10s} Rxa1 {+0.85/25 3.4s}
22. Rxa1 {+1.77/15 11s} e5 {+0.77/26 11s} 23. Qxh6 {-0.31/17 11s}
Qg7 {+0.83/24 3.4s} 24. Qxg7+ {-2.28/18 12s} Kxg7 {+0.83/20 0.60s}
25. Bxb5 {-1.94/20 12s} Ne7 {+0.82/28 18s} 26. Re1 {-1.62/19 13s}
e4 {+1.37/21 3.7s} 27. g4 {-1.62/21 13s} Ng6 {+1.80/21 4.1s}
28. Nd2 {-2.29/17 14s} e3 {+1.94/24 4.2s} 29. fxe3 {-3.78/17 14s}
dxe3 {+2.02/23 3.4s} 30. Nb3 {-3.05/18 15s} f4 {+2.33/24 3.1s}
31. Be2 {-4.10/19 15s} Ne5 {+2.40/26 3.6s} 32. Rf1 {-4.04/15 16s}
f3 {+2.50/26 3.4s} 33. Rxf3 {-6.73/20 16s} Nxf3+ {+2.51/25 6.3s}
34. Bxf3 {-6.67/20 17s} Rd6 {+2.58/25 3.8s} 35. Nc5 {-7.27/19 17s}
Rxb6 {+2.62/26 3.9s} 36. Nd3 {-7.35/18 18s} Rd6 {+3.21/22 3.3s}
37. Nf4 {-7.27/18 16s} Rd4 {+3.40/23 3.0s} 38. Ng2 {-8.21/19 11s}
Rxb4 {+3.52/22 4.1s} 39. Nxe3 {-7.85/18 8.0s} b5 {+3.58/19 2.7s}
40. Kf2 {-8.06/17 6.0s} Rb2+ {+3.83/20 4.6s} 41. Kg3 {-7.35/18 5.1s}
b4 {+3.99/18 2.7s} 42. g5 {-7.28/16 4.2s} b3 {+4.51/21 3.6s}
43. h4 {-7.42/15 3.8s} Rd2 {+4.59/21 3.0s} 44. h5 {-5.88/16 3.5s}
Rd3 {+5.72/19 3.1s} 45. h6+ {-6.36/15 3.3s} Kh8 {+6.15/23 4.3s}
46. Nc4 {-6.76/15 3.4s} Bb7 {+6.51/18 3.1s} 47. Ne5 {-9.24/14 3.3s}
Rxf3+ {+7.63/21 2.9s} 48. Kg4 {-44.68/16 3.2s} b2 {+10.64/21 3.8s}
49. Nxf3 {-44.77/14 3.3s} b1=Q {+13.33/20 2.7s} 50. Nh4 {-43.74/14 3.1s}
Qe4+ {+M15/36 5.9s} 51. Kg3 {-98.83/14 3.7s} Qe3+ {+M13/49 6.9s}
52. Kg4 {-109.65/16 4.2s} Bc8+ {+M11/58 6.1s} 53. Nf5 {-110.67/15 4.3s}
Kh7 {+M7/96 1.8s} 54. g6+ {-M6/127 1.3s} Kxg6 {+M5/96 0.067s}
55. h7 {-M4/127 1.5s} Bxf5+ {+M3/96 0.050s} 56. Kh4 {-113.56/1 0.029s}
Qf2# {+M1/96 0.070s, Black mates} 0-1
```

[ i'm on Xubuntu 22.04 ]

**Comment by Gourab-Ghosh** [comment]
@tissatussa Thank you for pointing out this. I am aware of this because in some position my engine cannot find the best move whereas it returns second or third best move. I have previously tried to solve it but couldn't detect where the bug is.

And regarding the time management, it is a long process of tweaking and testing. I believe that there are a lot of optimisations possible in my chess engine. So I have just made a basic time management system to test the performance of my chess engine on Lichess. So if anyone else works on that and creates a pull request the I will appreciate it very much, but for now I am not planning to tweak it unless I find it really necessary. Once my engine becomes stronger, I may try then.

**Comment by tissatussa** [comment]
> ..in some position my engine cannot find the best move whereas it returns second or third best move. I have previously tried to solve it but couldn't detect where the bug is..

oops .. maybe rewrite some part of the code ? This might lower the overall strength greatly ?

> ..not planning to tweak it unless I find it really necessary. Once my engine becomes stronger, I may try then..

but spending efficient time every move in every position type will result in a stronger engine ?

**Comment by Gourab-Ghosh** [comment]
@tissatussa Regarding rewriting the code, this can introduce new bugs which I had to found a hard time to solve after much testing and tweaking. You can see the video [Coding Adventure: Making a Better Chess Bot](https://www.youtube.com/watch?v=_vqlIPDR2TU) by [Sebastian Lague](https://www.youtube.com/@SebastianLague) and you can see how many unexpected bugs he faced which are difficult to debug as well, unless you sit and watch games played by your engine one by one and then debug with different test cases and then find the problem. I do not want to face these kind of bugs again. I will try to find why this error is happening without rewriting the code.

Regarding the time management of the engine, you are absolutely right that making the time management efficient will result in increase of the rating of the engine. It is not that I do not want to work on it. But I am prioritizing other possible developments over it. I have recently realised that I should publish my engine in crates.io so that one can use it as a library. And it is still in beta version, so I am just modifying the code nowadays to make it more user friendly and also adding more features like multipv, chess960 and maybe atomic chess in future as well. After I am satisfied with this, I may again start working on making my engine stronger.

**Comment by Gourab-Ghosh** [comment]
@tissatussa Huge eval switch bug fixed (I think so).
